import os
import json
import re

# Import the validated Cloudera Impala execution utility
from app.tools.impala_client import execute_query

def execute_banking_query(sql_query: str) -> str:
    """
    Executes a read-only Cloudera Impala SELECT statement against the live 
    analytical warehouse and returns rows formatted as a JSON string.
    Only SELECT queries are authorized.
    """
    # 1. Clean markdown wrappers while preserving original query text & comments
    query = sql_query.strip()
    query = re.sub(r"^```(?:sql)?", "", query, flags=re.IGNORECASE)
    query = re.sub(r"```$", "", query).strip()
    
    # Optional: Log or print the exact original query generated by the agent
    print(f"📝 Executing Agent Query:\n{query}")

    # 2. Create a temporary clean copy ONLY used for security guardrail inspection
    clean_query = re.sub(r"--.*$", "", query, flags=re.MULTILINE)
    clean_query = re.sub(r"/\*.*?\*/", "", clean_query, flags=re.DOTALL).strip()
    clean_query = clean_query.rstrip(";").strip()
    clean_query_lower = clean_query.lower()
    
    # --- MANDATORY SECURITY GUARDRAIL (Evaluated on clean_query) ---
    forbidden_keywords = ["insert", "update", "delete", "drop", "alter", "truncate", "create", "merge"]
    
    has_forbidden_word = any(
        re.search(rf"\b{kw}\b", clean_query_lower) for kw in forbidden_keywords
    )
    
    is_read_only_start = clean_query_lower.startswith("select") or clean_query_lower.startswith("with")
    
    if has_forbidden_word or not is_read_only_start:
        return "Security Violation Error: Only read-only SELECT queries are authorized on this endpoint."
        
    try:
        # 3. Pass the ORIGINAL query (comments included) to Impala and execution logs
        raw_result = execute_query(query)
        
        records = raw_result.get("rows", [])
        return json.dumps(records, default=str)
            
    except Exception as e:
        return f"Cloudera Impala Engine Error: {str(e)}"