from __future__ import annotations

from app.tools.config import settings
from shared.embed_client import get_embedding_vector, rerank_documents as shared_rerank
from shared.qdrant_client import QdrantClient
from shared.cml_auth import get_cml_token


def search_documents(query: str, collection_name: str, top_k: int = 5) -> list[dict]:
    """
    Queries Qdrant vector store using embeddings generated by the remote embed-rerank microservice.
    Normalizes response array into standard dictionary formats.
    """
    qdrant_url = settings.qdrant_server_url.rstrip("/")
    cml_token = get_cml_token()

    try:
        # 1. Fetch query vector remotely from embed-rerank microservice
        query_vector = get_embedding_vector(query, cml_token=cml_token)

        # 2. Search Qdrant using the shared client
        client = QdrantClient(base_url=qdrant_url, token=cml_token)
        results = client.search(collection_name, query_vector, top_k=top_k, token=cml_token)

        if results and "error" in results[0]:
            return results

        # 3. Parse response payload
        output = []
        for item in results:
            payload_data = item.get("payload", {})
            score = round(float(item.get("score", 0.0)), 4) if item.get("score") is not None else None

            source_file = payload_data.get("source_file", payload_data.get("title", "Unknown_Document"))
            page_num = payload_data.get("page", "?")
            doc_text = payload_data.get("page_content", payload_data.get("excerpt", ""))

            output.append({
                "document_id": str(item.get("id", "unknown")),
                "title": f"{source_file} (halaman {page_num})" if page_num != "?" else source_file,
                "excerpt": doc_text[:400] if doc_text else "",
                "page_content": doc_text,  # Keep the full text for the reranker
                "score": score,
                "raw_payload": payload_data
            })

        return output

    except Exception as e:
        print(f"⚠️ Vector search operational failure: {str(e)}")
        return [{"error": f"Vector Store Failure: {str(e)}"}]


def rerank_documents(query: str, raw_documents: list[dict], top_n: int = 5) -> list[dict]:
    """
    Reranks candidate document snippets remotely via the embed-rerank Cross-Encoder microservice.
    """
    if not raw_documents:
        return []

    cml_token = get_cml_token()

    # doc_texts = [d.get("excerpt", "") for d in raw_documents]
    doc_texts = [d.get("page_content", d.get("excerpt", "")) for d in raw_documents]

    try:
        reranked_scores = shared_rerank(
            query=query,
            documents=doc_texts,
            cml_token=cml_token,
            top_n=top_n,
        )

        sorted_docs = []
        for item in reranked_scores:
            orig_doc = raw_documents[item["index"]]
            orig_doc["rerank_score"] = round(float(item["score"]), 4)
            sorted_docs.append(orig_doc)

        return sorted_docs
    except Exception as e:
        print(f"⚠️ Reranking operational failure: {str(e)}. Returning raw vector results.")
        return raw_documents[:top_n]