litellm_settings:
  drop_params: true

general_settings:
  # master_key: os.environ/LITELLM_MASTER_KEY

model_list:
  - model_name: os.environ/CML_MODEL_NAME
    litellm_params:
      model: os.environ/CML_MODEL_NAME
      custom_llm_provider: openai
      api_base: os.environ/AI_INFERENCE_URL
      api_key: os.environ/CDP_TOKEN
      ssl_verify: false
      request_timeout: 3600
      num_retries: 3

router_settings:
  routing_strategy: simple-shuffle
  timeout: 3600
  num_retries: 3